appName: fake-data-rest-api
namespace: default
replicas: 1
image:
  repository: 674059452637.dkr.ecr.us-east-1.amazonaws.com/prod-fake-data
  tag: latest
containerPort: 8080
springProfile: prod
service:
  type: ClusterIP
  port: 80
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"