appName: fake-data-rest-api
namespace: argocd
replicas: 1
image:
  repository: 674059452637.dkr.ecr.us-east-1.amazonaws.com/nonprod-fake-data
  tag: "setup_github_actions_15942174811"
containerPort: 8080
springProfile: nonprod
service:
  type: LoadBalancer # LoadBalancer hoặc ClusterIP
  port: 80
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"