apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount | default 2 }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: {{ .Values.appName }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        ports:
        - containerPort: {{ .Values.containerPort | default 8080 }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ .Values.springProfile | default "prod" }}
        - name: AWS_REGION
          value: {{ .Values.awsRegion }}
        - name: cloud.aws.s3.bucket
          value: {{ .Values.s3BucketName }}
        - name: cloud.aws.dynamodb.table
          value: {{ .Values.dynamodbTableName }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu | default "500m" }}
            memory: {{ .Values.resources.limits.memory | default "512Mi" }}
          requests:
            cpu: {{ .Values.resources.requests.cpu | default "200m" }}
            memory: {{ .Values.resources.requests.memory | default "256Mi" }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path | default "/actuator/health/liveness" }}
            port: {{ .Values.containerPort | default 8080 }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds | default 30 }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds | default 10 }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds | default 5 }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold | default 3 }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path | default "/actuator/health/readiness" }}
            port: {{ .Values.containerPort | default 8080 }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds | default 10 }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds | default 5 }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds | default 5 }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold | default 3 }}